---
- name: install ucsschool app
  shell: "univention-app install ucsschool --skip-checks must_have_valid_license --noninteractive --username Administrator \
  --pwdfile <(echo {{ rootpassword }})"
  args:
      executable: /bin/bash
  tags:
    - ucsschool
- name: 
  template:
     src: "templates/setup.j2"
     dest: "/tmp/ucsschool.py"
  tags:
    - ucsschool
- name: run ucsschool installation
  shell: "/usr/bin/python2.7 /tmp/ucsschool.py"
  args:
    executable: /bin/bash
  tags:
    - ucsschool
  notify:
    - restart univention-management-console-server
    - restart univention-management-console-web-server
